# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G
org.gradle.parallel=true

# Fabric Properties
# check these on https://fabricmc.net/develop
minecraft_version=26.2
loader_version=0.19.4
loom_version=1.17-SNAPSHOT

# Mod Properties
mod_version=1.9.0
maven_group=me.wolfii
archives_base_name=SmoothScrollingRefurbished

# Dependencies
modmenu_version=20.0.1
